# Generated by Django 4.2.7 on 2024-02-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.CharField(choices=[('Select', 'Select'), ('View', 'View'), ('Edit', 'Edit'), ('Delete', 'Delete')], default='Select', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Update_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
