# Generated by Django 5.0.1 on 2024-02-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=1000, null=True)),
                ('quantity', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
